### ISSUE TITLE
The original Safari Zone seems kinda pointless now

### ISSUE THREAD

**Issue by RobynLlama** [RobynLlama/LetsgoGB#38]
The new Safari Zone will not track balls or steps and kick you out, instead it'll be a fee each time you wish to enter the area. I'm also planning to move some pokemon out into the wild and bring in some version exclusives to make it worthwhile. ~~Finally I'd like to add a mechanic where entering the Safari Zone gives the player an Entry Ticket item. Save up enough of these and you get a loyalty reward bonus, wow! 😸~~

**Comment by Crunchepillar** [comment]
Update to entry ticket mechanic idea [wip]:
- When the player enters the Safari Zone and catches x pokemon the Safari Zone game ends and they get a reward ticket.
- Reward tickets can be traded for prizes at the Safari Zone gate (re-use game corner prize logic)
- Possible Rewards
  - Rare Candy
  - Other Starter Mons
  - PokeBox item (See #41 )
