### ISSUE TITLE
Invalid move IDs with transform

### ISSUE THREAD

**Issue by RobynLlama** [RobynLlama/LetsgoGB#53]
If a Ditto transforms into another Pokémon and then switches around the copied moves with the SELECT button, after the battle the Ditto will not have Transform and will instead have --. This can also be done with other Pokémon by having them use Mimic on Transform, or use Transform directly, such as Mew.

**Comment by Crunchepillar** [comment]
Solution: Disable reordering moves with the SELECT button while the active mon has its transformed flag set.
