### ISSUE TITLE
Multi-turn moves are fundamentally flawed

### ISSUE THREAD

**Issue by RobynLlama** [RobynLlama/LetsgoGB#9]
If possible, stop multi-turn moves from locking the defending mon out of combat. If not possible.. I dunno. Maybe import move tweaks from DefEd?

**Comment by Crunchepillar** [comment]
Start by removing play-turn lockout when hit by or when using multi-turn moves

https://github.com/Crunchepillar/LetsgoGB/blob/487457421b9c29faef9df6b9c89ef3a249ed34fc/engine/battle/core.asm#L426

Then remove enemy-turn lockout

https://github.com/Crunchepillar/LetsgoGB/blob/487457421b9c29faef9df6b9c89ef3a249ed34fc/engine/battle/core.asm#L3174
